version: '3'

networks:
  db-tier:
    external: true

services:
  webtorrent-nest:
    volumes:
      - ${WEBTORRENT_VOLUME_PATH}:/webtorrent   
    image: 'fiendofsound/webtorrent-nest:main'
    environment:
      - PG_URL=${PG_URL}
      - ENABLE_LOGS=${ENABLE_LOGS}
      - PORT=7071
    ports:
      - "7071:7071"
    networks:
      - db-tier
      - default