version: '3'

networks:
  db-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    networks:
      - db-tier
    volumes:
      - ${REDIS_VOLUME_PATH}:/bitnami/redis/data
    ports:
      - "127.0.0.1:6379:6379"
  pexels-api:   
    depends_on:
      - redis 
    image: 'fiendofsound/webtorrent-nest:main'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASSWORD}
      - PORT=7071
    ports:
      - "7071:7071"
    networks:
      - db-tier
      - default